# config/routes.yaml

# the "app_lucky_number" route name is not important yet
app_lucky_number:
    path: number
    controller: App\Controller\LuckyController::number

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
